BIN=VoltageRatioInputExample
SRCS=VoltageRatioInput_Example.c ../Common/PhidgetHelperFunctions.c
LIBS=-lphidget22
LIBDIR=
INCDIR=-I../Common

CFLAGS=-ggdb3 -Wall

all:
	${CC} ${CFLAGS} -o ${BIN} ${SRCS} ${INCDIR} ${LIBDIR} ${LIBS}
